name: Checks

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: Set up protoc
        uses: Arduino/actions/setup-protoc@master
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run checks
        run: |
          # add requirements
          sudo apt install portaudio19-dev
          pip install --upgrade pip poetry setuptools
          python3.6 -m venv ~/pyenv
          . ~/pyenv/bin/activate
          pip install -r requirements.qt
          (cd .. && git clone --depth 1 https://github.com/ankitects/anki-proto.git)
          (cd .. && git clone --depth 1 https://github.com/ankitects/anki-lib-rust.git)
          (cd .. && git clone --depth 1 https://github.com/ankitects/anki-py-bindings.git && cd anki-py-bindings && make build BUILDFLAGS="")
          pip install ../build/ankirspy*
          (cd .. && git clone --depth 1 https://github.com/ankitects/anki-lib-python.git && cd anki-lib-python && make build)
          pip install ../build/*.whl

          # check
          make build check

          # make sure global install works
          deactivate
          pip install ../build/*.whl
          cd .. && python -c 'import aqt'
